In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('breastcancer.csv')
dataset.head()

Sample code number  Clump thickness  ...  Mitosis  Class
0             1000025                5  ...        1      2
1             1002945                5  ...        1      2
2             1015425                3  ...        1      2
3             1016277                6  ...        1      2
4             1017023                4  ...        1      2

[5 rows x 11 columns]

In [3]:
X = dataset.iloc[:, 1:-1].to_numpy()
y = dataset.iloc[:, -1].to_numpy()
X[23:25, :]

array([[ 8.,  4.,  5.,  1.,  2., nan,  7.,  3.,  1.],
       [ 1.,  1.,  1.,  1.,  2.,  1.,  3.,  1.,  1.]])

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [5]:
#Add feature scaling, not required
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'median')
X_train = imputer.fit_transform(X_train)
X_train[23:25,:]

array([[2., 3., 1., 1., 5., 1., 1., 1., 1.],
       [1., 1., 1., 1., 5., 1., 3., 1., 1.]])

In [6]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [7]:
#Prepping test data
X_test = imputer.transform(X_test)

In [8]:
y_pred = classifier.predict(X_test)

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[107   5]
 [  6  57]]


In [10]:
roc_auc_score(y_test, y_pred)

0.9300595238095237

In [11]:
#Accuracy = (TP + TN) / (TP + TN + FP + FN)
accuracy_score(y_test, y_pred)

0.9371428571428572

In [12]:
#Sensitivity = TP / (TP + FN) ability to determine the patient cases (malignant tumors) correctly
57/(57+5)

0.9193548387096774

In [13]:
#Specificity = TN / (TN + FP)  ability to determine the healthy cases (benign tumors) correctly
107/(107+6)

0.9469026548672567

In [14]:
#Precision = TP / (TP + FP) the number of correct positive predictions made
57/(57+6)

0.9047619047619048