<a href="https://colab.research.google.com/github/mehtamishah/Breast-Cancer-Detection/blob/main/bc_knearestneighborsclassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
import pandas as pd

In [17]:
dataset = pd.read_csv('breast cancer.csv')
dataset.head()

Sample code number  Clump thickness  ...  Mitosis  Class
0             1000025                5  ...        1      2
1             1002945                5  ...        1      2
2             1015425                3  ...        1      2
3             1016277                6  ...        1      2
4             1017023                4  ...        1      2

[5 rows x 11 columns]

In [18]:
X = dataset.iloc[:, 1:-1].to_numpy()
y = dataset.iloc[:, -1].to_numpy()
X[23:25, :]

array([[ 8.,  4.,  5.,  1.,  2., nan,  7.,  3.,  1.],
       [ 1.,  1.,  1.,  1.,  2.,  1.,  3.,  1.,  1.]])

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [20]:
unique_elements, counts_elements = np.unique(y_train, return_counts=True)
print(np.asarray((unique_elements, counts_elements)))
#(2 for benign, 4 for malignant)

[[  2   4]
 [346 178]]


In [21]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'median')
X_train = imputer.fit_transform(X_train)
X_train[23:25,:]

array([[2., 3., 1., 1., 5., 1., 1., 1., 1.],
       [1., 1., 1., 1., 5., 1., 3., 1., 1.]])

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)

In [23]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [24]:
#Prepping test data
X_test = imputer.transform(X_test)
X_test = sc.transform(X_test)

In [25]:
y_pred = classifier.predict(X_test)

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
# TP malignant 61
# TN benign 109
# FP 2
# FN 3

[[109   3]
 [  2  61]]


In [27]:
roc_auc_score(y_test, y_pred) #winner!!!

0.9707341269841271

In [28]:
#Accuracy = (TP + TN) / (TP + TN + FP + FN)
accuracy_score(y_test, y_pred)

0.9714285714285714

In [29]:
#Sensitivity = TP / (TP + FN) ability to determine the patient cases (malignant tumors) correctly
61/(61+3)

0.953125

In [30]:
#Specificity = TN / (TN + FP)  ability to determine the healthy cases (benign tumors) correctly
109/(109+2)

0.9819819819819819

In [31]:
#Precision = TP / (TP + FP) the number of correct positive predictions made
61/(61+2)

0.9682539682539683