<a href="https://colab.research.google.com/github/mehtamishah/Breast-Cancer-Detection/blob/main/bc_kernelSVMclassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv('breastcancer.csv')
dataset.head()

Sample code number  Clump thickness  ...  Mitosis  Class
0             1000025                5  ...        1      2
1             1002945                5  ...        1      2
2             1015425                3  ...        1      2
3             1016277                6  ...        1      2
4             1017023                4  ...        1      2

[5 rows x 11 columns]

In [ ]:
X = dataset.iloc[:, 1:-1].to_numpy()
y = dataset.iloc[:, -1].to_numpy()
X[23:25, :]

array([[ 8.,  4.,  5.,  1.,  2., nan,  7.,  3.,  1.],
       [ 1.,  1.,  1.,  1.,  2.,  1.,  3.,  1.,  1.]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'median')
X_train = imputer.fit_transform(X_train)
X_train[23:25,:]

array([[2., 3., 1., 1., 5., 1., 1., 1., 1.],
       [1., 1., 1., 1., 5., 1., 3., 1., 1.]])

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
#Prepping test data
X_test = imputer.transform(X_test)
X_test = sc.transform(X_test)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
#metric
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[108   4]
 [  3  60]]


0.96

In [ ]:
roc_auc_score(y_test, y_pred)

0.9583333333333334