<a href="https://colab.research.google.com/github/mehtamishah/Breast-Cancer-Detection/blob/main/bc_logisticregressionclassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv("breastcancer.csv")
dataset.head()

Sample code number  Clump thickness  ...  Mitosis  Class
0             1000025                5  ...        1      2
1             1002945                5  ...        1      2
2             1015425                3  ...        1      2
3             1016277                6  ...        1      2
4             1017023                4  ...        1      2

[5 rows x 11 columns]

In [ ]:
dataset.describe()

Sample code number  Clump thickness  ...     Mitosis       Class
count        6.990000e+02       699.000000  ...  699.000000  699.000000
mean         1.071704e+06         4.417740  ...    1.589413    2.689557
std          6.170957e+05         2.815741  ...    1.715078    0.951273
min          6.163400e+04         1.000000  ...    1.000000    2.000000
25%          8.706885e+05         2.000000  ...    1.000000    2.000000
50%          1.171710e+06         4.000000  ...    1.000000    2.000000
75%          1.238298e+06         6.000000  ...    1.000000    4.000000
max          1.345435e+07        10.000000  ...   10.000000    4.000000

[8 rows x 11 columns]

In [ ]:
dataset['Bare Nuclei'].isna().sum()

16

In [ ]:
dataset.dtypes

Sample code number            int64
Clump thickness               int64
Uniformity of cell size       int64
Uniformity of cell shape      int64
Marginal Adhesion             int64
Single Epithelial cell        int64
Bare Nuclei                 float64
Bland Chromatin               int64
Normal Nucleoli               int64
Mitosis                       int64
Class                         int64
dtype: object

In [ ]:
dataset['Class'].value_counts()

2    458
4    241
Name: Class, dtype: int64

In [ ]:
X = dataset.iloc[:, 1:-1].to_numpy()
y = dataset.iloc[:, -1].to_numpy()
X[23:25, :]

array([[ 8.,  4.,  5.,  1.,  2., nan,  7.,  3.,  1.],
       [ 1.,  1.,  1.,  1.,  2.,  1.,  3.,  1.,  1.]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'median')
X_train = imputer.fit_transform(X_train)
X_train[23:25,:]

array([[2., 3., 1., 1., 5., 1., 1., 1., 1.],
       [1., 1., 1., 1., 5., 1., 3., 1., 1.]])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
#Feature scaling is not required unlike for svr, but it will improve performance in this case

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train) #lower the C parameter more regularized the model (less overfitting)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
#Prepping test data
X_test = imputer.transform(X_test)
X_test = sc.transform(X_test)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[109   3]
 [  3  60]]


0.9657142857142857

In [ ]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, y_pred)

0.962797619047619