In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('breastcancer.csv')
dataset.head()

Sample code number  Clump thickness  ...  Mitosis  Class
0             1000025                5  ...        1      2
1             1002945                5  ...        1      2
2             1015425                3  ...        1      2
3             1016277                6  ...        1      2
4             1017023                4  ...        1      2

[5 rows x 11 columns]

In [3]:
X = dataset.iloc[:, 1:-1].to_numpy()
y = dataset.iloc[:, -1].to_numpy()
X[23:25, :]

array([[ 8.,  4.,  5.,  1.,  2., nan,  7.,  3.,  1.],
       [ 1.,  1.,  1.,  1.,  2.,  1.,  3.,  1.,  1.]])

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'median')
X_train = imputer.fit_transform(X_train)
X_train[23:25,:]

array([[2., 3., 1., 1., 5., 1., 1., 1., 1.],
       [1., 1., 1., 1., 5., 1., 3., 1., 1.]])

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)

In [7]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [8]:
#Prepping test data
X_test = imputer.transform(X_test)
X_test = sc.transform(X_test)

In [9]:
y_pred = classifier.predict(X_test)

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[106   6]
 [  2  61]]


In [11]:
roc_auc_score(y_test, y_pred)

0.9573412698412699

In [12]:
#Accuracy = (TP + TN) / (TP + TN + FP + FN)
accuracy_score(y_test, y_pred)

0.9542857142857143

In [13]:
#Sensitivity = TP / (TP + FN) ability to determine the patient cases (malignant tumors) correctly #Recall
61/(61+6)

0.9104477611940298

In [14]:
#Specificity = TN / (TN + FP)  ability to determine the healthy cases (benign tumors) correctly
106/(106+2)

0.9814814814814815

In [15]:
#Precision = TP / (TP + FP) the number of correct positive predictions made
61/(61+2)

0.9682539682539683