In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv('breastcancer.csv')
dataset.head()

Sample code number  Clump thickness  ...  Mitosis  Class
0             1000025                5  ...        1      2
1             1002945                5  ...        1      2
2             1015425                3  ...        1      2
3             1016277                6  ...        1      2
4             1017023                4  ...        1      2

[5 rows x 11 columns]

In [ ]:
X = dataset.iloc[:, 1:-1].to_numpy()
y = dataset.iloc[:, -1].to_numpy()
X[23:25, :]

array([[ 8.,  4.,  5.,  1.,  2., nan,  7.,  3.,  1.],
       [ 1.,  1.,  1.,  1.,  2.,  1.,  3.,  1.,  1.]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
#Feature scaling is not required and wont help but can add
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'median')
X_train = imputer.fit_transform(X_train)
X_train[23:25,:]

array([[2., 3., 1., 1., 5., 1., 1., 1., 1.],
       [1., 1., 1., 1., 5., 1., 3., 1., 1.]])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
#Prepping test data
X_test = imputer.transform(X_test)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[109   3]
 [  3  60]]


In [ ]:
roc_auc_score(y_test, y_pred)

0.962797619047619

In [ ]:
#Accuracy = (TP + TN) / (TP + TN + FP + FN)
accuracy_score(y_test, y_pred)

0.9657142857142857

In [ ]:
#Sensitivity = TP / (TP + FN) ability to determine the patient cases (malignant tumors) correctly #Recall
60/(60+3)

0.9523809523809523

In [ ]:
#Specificity = TN / (TN + FP)  ability to determine the healthy cases (benign tumors) correctly
109/(109+3)

0.9732142857142857

In [ ]:
#Precision = TP / (TP + FP) the number of correct positive predictions made
60/(60+3)

0.9523809523809523